# Project settings
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Program Files/Java/jdk-21

# Performance settings
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Paper settings
runPaperWeight=true