name: EnhancedCoreH
version: ${version}
main: org.arch.me.EnhancedCoreH
api-version: '1.21'
load: POSTWORLD
dependencies:
  - name: Vault
    load: BEFORE
    required: true
  - name: Essentials
    load: BEFORE
    required: false
